
---

- hosts: 192.168.13.132

  tasks:
  - name: Installation du serveur Apache et du PHP
    yum:
     name: "{{ item }}"
     state: present
    loop:
      - httpd
      - php
      - mariadb-server

  - name: Demarrage du serveur apache
    systemd:
     name: " {{ item }}"
     state: started
    loop: 
      - httpd
      - mariadb

  - name: Copie des fichiers php info
    copy:
     src: "{{ item }}"
     dest: /var/www/html
   loop:
     - index.php
     - create_db.php

 
